export const interests = [
	{ id: 'sport', label: 'Sport' },
	{ id: 'science', label: 'Science' },
	{ id: 'it', label: 'IT' },
	{ id: 'math', label: 'Math' },
	{ id: 'music', label: 'Music' },
	{ id: 'art', label: 'Art' },
	{ id: 'cooking', label: 'Cooking' },
	{ id: 'travel', label: 'Travel' },
	{ id: 'photography', label: 'Photography' },
	{ id: 'fashion', label: 'Fashion' },
	{ id: 'reading', label: 'Reading' },
	{ id: 'gaming', label: 'Gaming' },
	{ id: 'movies', label: 'Movies' },
	{ id: 'gardening', label: 'Gardening' },
	{ id: 'programming', label: 'Programming' },
	{ id: 'dancing', label: 'Dancing' },
	{ id: 'writing', label: 'Writing' },
	{ id: 'yoga', label: 'Yoga' },
	{ id: 'hiking', label: 'Hiking' },
	{ id: 'pets', label: 'Pets' },
] as const;
